[package]
name = "nesrs"
version = "0.1.0"
authors = ["Mark Glenn <mark.glenn@mbx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.1.0"
bitfield = "0.13.2"